# Generated by Django 3.1.6 on 2021-02-12 19:29

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', wagtail.core.fields.StreamField([('socials', wagtail.core.blocks.StructBlock([('social_name', wagtail.core.blocks.CharBlock(blank=True, help_text='Enter the name of the social media', max_length=50)), ('social_url', wagtail.core.blocks.URLBlock(blank=True, help_text='Enter the URL of the social media')), ('social_img', wagtail.images.blocks.ImageChooserBlock(blank=True, help_text='Enter image of the social media', null=True))]))])),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='socialmediasettings',
            name='site',
        ),
        migrations.DeleteModel(
            name='SocialMedia',
        ),
        migrations.DeleteModel(
            name='SocialMediaSettings',
        ),
    ]
