# Generated by Django 3.1.6 on 2021-02-12 21:39

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_auto_20210212_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='body',
            field=wagtail.core.fields.StreamField([('social', wagtail.core.blocks.StructBlock([('social_name', wagtail.core.blocks.CharBlock(blank=True, help_text='Enter the name of the social media', max_length=50, null=True)), ('social_url', wagtail.core.blocks.URLBlock(blank=True, help_text='Enter the URL of the social media')), ('social_img', wagtail.images.blocks.ImageChooserBlock(blank=True, help_text='Enter image of the social media', null=True))], template='streams/socials.html'))]),
        ),
    ]
