# Generated by Django 3.1.6 on 2021-02-12 22:32

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('settings', '0003_auto_20210212_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='body',
            field=wagtail.core.fields.StreamField([('social', wagtail.core.blocks.StructBlock([('social_name', wagtail.core.blocks.CharBlock(help_text='Enter the name of the social media', max_length=50, required=False)), ('social_url', wagtail.core.blocks.URLBlock(help_text='Enter the URL of the social media', required=False)), ('social_img', wagtail.images.blocks.ImageChooserBlock(help_text='Enter image of the social media', required=False))], template='streams/socials.html'))]),
        ),
        migrations.CreateModel(
            name='ContactSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', wagtail.core.fields.RichTextField(blank=True)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
