# Generated by Django 3.1.6 on 2021-02-15 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('settings', '0006_footerctasettings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FooterCTASettings',
            new_name='FooterCTASetting',
        ),
    ]
