# Generated by Django 3.1.6 on 2021-02-15 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_auto_20210215_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='footerctasetting',
            name='page_name',
            field=models.CharField(blank=True, help_text='Contact Page Name', max_length=50),
        ),
    ]
