# Generated by Django 3.1.6 on 2021-02-04 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('home', '0004_auto_20210203_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='button',
            field=models.ForeignKey(blank=True, help_text='Page Chooser Panel', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
    ]
