# Generated by Django 3.1.6 on 2021-02-08 22:15

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.StreamField([('title', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='This is a Struct Block', required=True))])), ('cards', wagtail.core.blocks.StructBlock([('cards', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Bold text title for this card, max length is 100 characters', max_length=100)), ('text', wagtail.core.blocks.TextBlock(help_text='Paragraph text for this card, max length is 500 characterss', max_length=500))])))]))], blank=True, null=True),
        ),
    ]
