# Generated by Django 3.1.6 on 2021-02-09 01:31

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210208_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.StreamField([('title', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='This is a Struct Block', required=True))])), ('cards', wagtail.core.blocks.StructBlock([('cards', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Bold text title for this card, max length is 100 characters', max_length=100)), ('text', wagtail.core.blocks.TextBlock(help_text='Paragraph text for this card, max length is 500 characterss', max_length=500)), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='This image will be automatically cropped to 570px by 370px')), ('link', wagtail.core.blocks.StructBlock([('link_title', wagtail.core.blocks.TextBlock(max_length=100)), ('internal_page', wagtail.core.blocks.PageChooserBlock(help_text='Enter a Link', required=False)), ('external_page', wagtail.core.blocks.CharBlock(help_text='Enter an external page', required=False))], help_text='Enter a Link or an external Page'))])))])), ('images', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(help_text='Image will be cropped 570px by 370px', required=True)), ('image_alignment', wagtail.core.blocks.ChoiceBlock(choices=[('left', 'Image to the left'), ('right', 'Image to the right')], help_text='Image on the left with text on the right, Image in the right with text on the left')), ('title', wagtail.core.blocks.CharBlock(default='Title', help_text='Max length is 50 characters...', max_length=50)), ('text', wagtail.core.blocks.CharBlock(help_text='Max length is 500 characters...', max_length=500, required=False)), ('link', wagtail.core.blocks.StructBlock([('link_title', wagtail.core.blocks.TextBlock(max_length=100)), ('internal_page', wagtail.core.blocks.PageChooserBlock(help_text='Enter a Link', required=False)), ('external_page', wagtail.core.blocks.CharBlock(help_text='Enter an external page', required=False))]))]))], blank=True, null=True),
        ),
    ]
