# Generated by Django 3.1.6 on 2021-02-09 23:46

from django.db import migrations
import streams.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flexpage',
            name='body',
            field=wagtail.core.fields.StreamField([('title', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='This is a Struct Block', required=True))])), ('cards', wagtail.core.blocks.StructBlock([('cards', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Bold text title for this card, max length is 100 characters', max_length=100)), ('text', wagtail.core.blocks.TextBlock(help_text='Paragraph text for this card, max length is 500 characterss', max_length=500)), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='This image will be automatically cropped to 570px by 370px')), ('link', wagtail.core.blocks.StructBlock([('link_title', wagtail.core.blocks.TextBlock(max_length=100)), ('internal_page', wagtail.core.blocks.PageChooserBlock(help_text='Enter a Link', required=False)), ('external_page', wagtail.core.blocks.CharBlock(help_text='Enter an external page', required=False))], help_text='Enter a Link or an external Page'))])))])), ('images', wagtail.core.blocks.StructBlock([('imgtexts', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(help_text='Image will be cropped 570px by 370px', required=True)), ('image_alignment', wagtail.core.blocks.ChoiceBlock(choices=[('left', 'Image to the left'), ('right', 'Image to the right')], help_text='Image on the left with text on the right, Image in the right with text on the left')), ('title', wagtail.core.blocks.CharBlock(default='Title', help_text='Max length is 50 characters...', max_length=50)), ('text', wagtail.core.blocks.CharBlock(help_text='Max length is 500 characters...', max_length=500, required=False)), ('link', wagtail.core.blocks.StructBlock([('link_title', wagtail.core.blocks.TextBlock(max_length=100)), ('internal_page', wagtail.core.blocks.PageChooserBlock(help_text='Enter a Link', required=False)), ('external_page', wagtail.core.blocks.CharBlock(help_text='Enter an external page', required=False))]))])))])), ('cta', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Max Characters for the title is 200 characters', max_length=200)), ('link', wagtail.core.blocks.StructBlock([('link_title', wagtail.core.blocks.TextBlock(max_length=100)), ('internal_page', wagtail.core.blocks.PageChooserBlock(help_text='Enter a Link', required=False)), ('external_page', wagtail.core.blocks.CharBlock(help_text='Enter an external page', required=False))]))])), ('testimonials', wagtail.snippets.blocks.SnippetChooserBlock(target_model='testimonials.Testimonial', template='streams/testimonial_block.html')), ('table', streams.blocks.PricingTableBlock(table_options={'autoColumnSize': False, 'colHeaders': False, 'contextMenu': ['row_above', 'row_below', '---------', 'col_left', 'col_right', '---------', 'remove_row', 'remove_col', '---------', 'undo', 'redo'], 'editor': 'text', 'height': 108, 'minSpareRows': 0, 'renderer': 'text', 'rowHeaders': False, 'startCols': 4, 'startRows': 4, 'stretchH': 'all'}))], blank=True, null=True),
        ),
    ]
